---
apiVersion: v1
items:
- kind: Service
  metadata:
    name: foocorp-manager
  spec:
    selector:
      serviceName: foocorp-manager
- kind: Deployment
  metadata:
    name: foocorp-manager
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: foocorp-manager
      spec:
        containers:
        - env:
            name: SERVICE_CONF
            value: |-
              {
                  "customerName": "foocorp",
                  "database": "user-db.databricks.us-west-2.rds.amazonaws.com"
              }
          image: manager:2.42-rc1
          name: default
          resources:
            requests:
              cpu: 500m
              memory: 250Mi
kind: List
